{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Introduction to CAD Modeling with CadQuery"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Welcome to the world of CAD modeling using CadQuery in Visual Studio Code (VS Code)! In this lesson, you'll embark on an exciting journey into the realm of computer-aided design (CAD), where you'll learn how to create 3D models programmatically using Python and CadQuery.\n",
    "\n",
    "## Overview\n",
    "\n",
    "CAD modeling is an essential skill in various fields such as engineering, architecture, product design, and more. Traditionally, CAD software involves graphical user interfaces (GUIs) where users interactively create and manipulate geometric shapes. However, with CadQuery, you can harness the power of programming to automate and customize your designs.\n",
    "\n",
    "## Prerequisites\n",
    "\n",
    "Before diving into this lesson, it's helpful to have some basic understanding of programming concepts, particularly in Python. Familiarity with VS Code and its Python extension will also be beneficial. However, even if you're new to programming, don't worry! This lesson will guide you through step-by-step.\n",
    "\n",
    "## Lesson Structure\n",
    "\n",
    "This lesson is structured into two main sections: **Basic Tools** and **Intermediate Examples**. Each section contains a series of example scripts that you can run and modify to grasp the fundamental concepts of CadQuery. An **Advanced Example** is also provided, but in a separate file called `Advanced_Example_Hexapod.ipynb`.\n",
    "\n",
    "### Basic Tools\n",
    "\n",
    "1. **Cube**: Learn how to create a simple cube.\n",
    "2. **Drilling Holes**: Explore the process of drilling holes into objects.\n",
    "3. **Splines & Revolve**: Understand how to create shapes using splines and revolve operations.\n",
    "4. **Lofts**: Discover how to create complex surfaces by lofting between profiles.\n",
    "5. **Sweeps**: Learn about creating shapes by sweeping a profile along a path.\n",
    "6. **Helix**: Explore the creation of helical shapes.\n",
    "\n",
    "### Intermediate Examples\n",
    "\n",
    "1. **Complex Surfaces**: Delve into more advanced techniques for creating intricate surfaces.\n",
    "2. **Cycloid Gear**: Learn how to design a cycloid gear, a complex mechanical component.\n",
    "\n",
    "## Project Challenge\n",
    "\n",
    "After exploring the provided examples, you'll have the opportunity to take on a project challenge. Use your newfound skills to design something unique of your own. This project challenge will encourage you to apply what you've learned and unleash your creativity in CAD modeling.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Getting Started\n",
    "\n",
    "Before you begin, it is important to do the following:\n",
    "1. Set up your virtual environment:\n",
    "    - Click `Terminal` -> `New Terminal`\n",
    "    - In the terminal that appears below, type `sudo apt install python3-venv` (you may need to press `y` and enter to accept an installation)\n",
    "    - Once it's done installing, type `python3 -m venv ps` to create a virtual environment named `ps` (you may use any other name you like)\n",
    "    - You may see a window pop up that says \"We noticed a new environment has been created. Do you want to select it for the workspace folder?\", if so, select `Yes`.\n",
    "    - Restart VS Code\n",
    "2. Activate your virtual environment:\n",
    "    - Click `Terminal` -> `New Terminal`\n",
    "    - In the terminal, type `source ps/bin/activate` and press enter\n",
    "3. Install and set up the OCP CAD Viewer extension:\n",
    "    - Click on the `Extensions` icon in the left sidebar\n",
    "    - Type `OCP CAD Viewer` in the search bar\n",
    "    - Click `Install` on the resulting extension\n",
    "    - Click on the newly added OCP CAD Viewer icon in the left sidebar\n",
    "    -  In the sidebar menu, you should see towards the bottom `LIBRARY MANAGER`. Below that select the download button that appears to the right of the following:\n",
    "        - build123d\n",
    "        - cadquery\n",
    "        - ipykernel\n",
    "        - ocp_tessellate\n",
    "        - ocp_vscode\n",
    "\n",
    "        For each, select `pip` and `yes` when prompted.\n",
    "\n",
    "4. Once this is done, `pip install` the following additional libraries:\n",
    "    - jupyter_cadquery\n",
    "    - cadquery_massembly\n",
    "5. Restart VS Code again to make sure the installations have taken effect.\n",
    "6. In the top right corner of this window, press the `Select Kernal` button and choose your virtual environment.\n",
    "7. Activate the OCP CAD Viewer:\n",
    "    - Click again on the OCP CAD Viewer icon in the left sidebar\n",
    "    - In the sidebar menu, you should see `ocp_vscode` towards the top. To the right of it, you can press the second botton the right `OCP CAD Viwer: Open viewer (button)`.\n",
    "\n",
    "A window should have popped up that will be able to view your CAD designs (once you run them). Now you should be ready to go!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## How to use this notebook\n",
    "\n",
    "To run each code cell, click on the play button to the left of the cell. If you followed the setup instructions completely, you should see your designs show up in the recentlly opened window."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Import Libraries"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The cell below imports the necessary libraries to run the later code and then opens the port that allows you to view the CAD parts. Running this cell will not produce a CAD part, but will allow the later cells to do it."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import necessary modules for CAD modeling with CadQuery in VS Code.\n",
    "# The `ocp_vscode` module provides integration with VS Code for CadQuery.\n",
    "# `cadquery` is the Python library used for parametric 3D modeling.\n",
    "# We also import mathematical functions like sin, cos, pi, sqrt, and floor for later use.\n",
    "\n",
    "from ocp_vscode import *\n",
    "import cadquery as cq\n",
    "from math import sin, cos, pi, sqrt, floor\n",
    "\n",
    "# Set the port number for communication between CadQuery and VS Code.\n",
    "# This allows CadQuery to communicate with the VS Code extension on the specified port.\n",
    "\n",
    "set_port(3939)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Basic Tools"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Cube"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "CadQuery is a powerful Python library for parametric 3D modeling, allowing you to create intricate geometric shapes programmatically. In this introduction, we'll start with the most basic geometry - a cube. Through this example, you'll learn about essential CadQuery functions and how to modify them to explore and create your own designs.\n",
    "\n",
    "### CadQuery Functions Explained\n",
    "\n",
    "1. `cq.Workplane()`\n",
    "\n",
    "The `cq.Workplane()` function is used to define a workplane, which is a 2D plane in 3D space where geometric operations are performed. You can specify the orientation of the workplane using parameters like `\"XY\"`, `\"XZ\"`, or `\"YZ\"`.\n",
    "\n",
    "2. `.box()`\n",
    "\n",
    "The `.box()` function is used to create a box-shaped solid. It takes three arguments: width, length, and height. These parameters define the dimensions of the box along the X, Y, and Z axes, respectively.\n",
    "\n",
    "3. `show()`\n",
    "\n",
    "The `show()` function is used to render 3D models in the VS Code interface. It takes the CadQuery object representing the 3D model as input. Additionally, you can provide optional parameters like `names` and `colors` to customize the appearance of the rendered model.\n",
    "\n",
    "### Modifying the Example\n",
    "\n",
    "To explore and modify the example, you can make changes to the dimensions of the cube by adjusting the arguments passed to the `.box()` function. Try changing the width, length, and height values to see how it affects the size of the cube. You can also change the `names` and `colors` provided.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a 3D model of a cube using CadQuery.\n",
    "# We start by defining a workplane in the XY plane and then create a box with dimensions 1x1x1.\n",
    "\n",
    "cube = cq.Workplane(\"XY\").box(1, 1, 1)\n",
    "\n",
    "# Render the 3D model of the cube.\n",
    "# The `show` function displays the 3D model in the VS Code interface.\n",
    "# We provide optional parameters like names and colors to customize the appearance of the model.\n",
    "\n",
    "show(cube, names=['cube'], colors=['lightgreen'])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Drilling Holes"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this example, we'll create a 3D block with customizable dimensions and features such as a center hole and counterbored holes for bolts. You'll learn how to parameterize the dimensions of the block and modify various attributes to create different designs.\n",
    "\n",
    "### Customization Parameters\n",
    "\n",
    "To facilitate customization, we define several parameters that control the dimensions and features of the block:\n",
    "\n",
    "- `length`: Length of the block.\n",
    "- `width`: Width of the block.\n",
    "- `thickness`: Thickness of the block.\n",
    "- `center_hole_dia`: Diameter of the center hole in the block.\n",
    "- `cbore_hole_diameter`: Diameter of the bolt shank/threads clearance hole.\n",
    "- `cbore_inset`: Distance from the edge where the counterbored holes are set.\n",
    "- `cbore_diameter`: Diameter of the bolt head pocket hole.\n",
    "- `cbore_depth`: Depth of the bolt head pocket hole.\n",
    "- `fillet_radius`: Radius of the exterior fillets.\n",
    "\n",
    "### Script Explanation\n",
    "\n",
    "1. **Establish Workplane**: The script starts by establishing a workplane on which the object will be built. It uses the X and Y origins, defining the positive Z direction as \"up\" and the negative Z direction as \"down\".\n",
    "\n",
    "2. **Drill Center Hole**: It selects the highest Z face and creates a new workplane on it. A center hole is then drilled through the block, automatically centered on the workplane.\n",
    "\n",
    "3. **Create Counterbored Holes**: Next, it selects the highest Z face again and creates a new workplane on it. A for-construction rectangle is created based on the block's overall dimensions. Then, counterbored holes are placed at each of the rectangle's vertices simultaneously.\n",
    "\n",
    "4. **Fillets**: Finally, the script applies fillets to the edges of the resulting geometry, giving it a smoother appearance.\n",
    "\n",
    "### Modifying the Example\n",
    "\n",
    "You can modify the parameters such as `length`, `width`, `thickness`, and others to change the dimensions and features of the block. Experiment with different values to create blocks of varying sizes and hole configurations.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# These can be modified rather than hardcoding values for each dimension.\n",
    "length = 80.0               # Length of the block\n",
    "width = 100.0               # Width of the block\n",
    "thickness = 10.0            # Thickness of the block\n",
    "center_hole_dia = 22.0      # Diameter of center hole in block\n",
    "cbore_hole_diameter = 2.4   # Bolt shank/threads clearance hole diameter\n",
    "cbore_inset = 12.0          # How far from the edge the cbored holes are set\n",
    "cbore_diameter = 4.4        # Bolt head pocket hole diameter\n",
    "cbore_depth = 2.1           # Bolt head pocket hole depth\n",
    "fillet_radius = 3.0         # Radiuis of the exterior fillets\n",
    "\n",
    "# Create a 3D block based on the dimensions above and add a 22mm center hold\n",
    "# and 4 counterbored holes for bolts\n",
    "result = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .box(length, width, thickness)\n",
    "    .faces(\">Z\")\n",
    "    .workplane()\n",
    "    .hole(center_hole_dia)\n",
    "    .faces(\">Z\")\n",
    "    .workplane()\n",
    "    .rect(length - cbore_inset, width - cbore_inset, forConstruction=True)\n",
    "    .vertices()\n",
    "    .cboreHole(cbore_hole_diameter, cbore_diameter, cbore_depth)\n",
    "    .edges(\"|Z\")\n",
    "    .fillet(fillet_radius)\n",
    ")\n",
    "\n",
    "# Displays the result of this script\n",
    "show(result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Splines"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this example, we'll create a 3D plate with a spline profile using CadQuery. You'll learn how to define a spline curve, extrude it to create a 3D shape, and visualize the result. Additionally, you'll explore an alternative method using the revolve operation to generate the plate.\n",
    "\n",
    "### Script Explanation\n",
    "\n",
    "1. **Establish Workplane**: The script starts by establishing a workplane to create the spline on. It uses the X and Y origins to define the workplane, with the positive Z direction as \"up\" and the negative Z direction as \"down\".\n",
    "\n",
    "2. **Define Spline Points**: Next, a list of points (`sPnts`) is defined, representing the coordinates through which the spline will pass.\n",
    "\n",
    "3. **Generate Plate with Spline**: The script generates a plate using the defined spline feature (`spline()`). The `includeCurrent=True` parameter ensures that the current position of the workplane is included in the spline, resulting in a closed entity.\n",
    "\n",
    "4. **Extrude**: The resulting wire profile is extruded to give it thickness and turn it into a plate. The `extrude()` function is used for this operation, with a specified extrusion depth of 0.5 units.\n",
    "\n",
    "5. **Alternative: Revolve Operation**: An alternative method using the revolve operation is provided as a comment. You can experiment with this alternative by commenting out the extrusion line and uncommenting the revolve line. This will create the plate by revolving the spline profile around an axis.\n",
    "\n",
    "### Modifying the Example\n",
    "\n",
    "You can modify the script by adjusting the coordinates of the spline points (`sPnts`) to create different spline profiles. Try adding or removing points, changing their positions, or altering the curvature to create various shapes. You can also change the extrude height or revolve angle / axis.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Establishes a workplane to create the spline on to extrude.\n",
    "s = cq.Workplane(\"XY\")\n",
    "\n",
    "# The points that the spline will pass through (x-y coordinates)\n",
    "sPnts = [\n",
    "    (2.75, 1.5),\n",
    "    (2.5, 1.75),\n",
    "    (2.0, 1.5),\n",
    "    (1.5, 1.0),\n",
    "    (1.0, 1.25),\n",
    "    (0.5, 1.0),\n",
    "    (0, 1.0),\n",
    "]\n",
    "\n",
    "# Generate plate with the spline feature\n",
    "r = s.lineTo(3.0, 0).lineTo(3.0, 1.0).spline(sPnts, includeCurrent=True).close()\n",
    "\n",
    "# Extrude to turn the wire into a plate\n",
    "result = r.extrude(0.5)\n",
    "\n",
    "# Try revolve instead by commenting out the last result line\n",
    "# (by putting a '#' in front of the line) and then uncommenting the line below\n",
    "# (by removing the '#')\n",
    "# result = r.revolve(360, axisStart=(0,0,0), axisEnd=(1,0,0))\n",
    "\n",
    "# Displays the result of this script\n",
    "show(result, reset_camera=Camera.CENTER)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Lofts"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this example, we'll create a lofted section between a rectangle and a circular section using CadQuery. You'll learn how to establish a workplane, create basic geometry, and use the loft operation to generate a smooth transition between two shapes.\n",
    "\n",
    "### Script Explanation\n",
    "\n",
    "1. **Establish Workplane**: The script starts by establishing a workplane on which the object will be built. It uses the named plane orientation \"front\" to define the workplane, with the positive Z direction as \"up\" and the negative Z direction as \"down\".\n",
    "\n",
    "2. **Create Base Box**: A plain box is created using the `box()` function. This box serves as the base for future geometry.\n",
    "\n",
    "3. **Select Top Face**: The top-most Z face of the box is selected using the `.faces(\">Z\")` selector.\n",
    "\n",
    "4. **Draw Circular Section**: A 2D circle is drawn at the center of the selected top face using the `.circle()` function.\n",
    "\n",
    "5. **Create Offset Workplane**: A workplane is created 3 mm above the face where the circle was drawn. This offset workplane will be used to draw the second circular section.\n",
    "\n",
    "6. **Draw Second Circle**: Another 2D circle is drawn on the new, offset workplane using the `.circle()` function.\n",
    "\n",
    "7. **Create Loft**: Finally, a loft operation is performed between the circle and the rectangle. This loft operation generates a smooth transition between the two shapes, creating the lofted section.\n",
    "\n",
    "### Modifying the Example\n",
    "\n",
    "You can modify the script by adjusting the parameters of the base box, circle, rectangle, and offset workplane to create different lofted sections. Experiment with changing the dimensions, shapes, positions, and orientations of the geometric elements to achieve various shapes and designs.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a lofted section between a rectangle and a circular section.\n",
    "result = (\n",
    "    cq.Workplane(\"front\")\n",
    "    .box(4.0, 4.0, 0.25)\n",
    "    .faces(\">Z\")\n",
    "    .circle(1.5)\n",
    "    .workplane(offset=3.0)\n",
    "    .rect(0.75, 0.5)\n",
    "    .loft(combine=True)\n",
    ")\n",
    "\n",
    "# Displays the result of this script\n",
    "show(result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Sweeps"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this example, we'll explore sweeping different shapes along a defined path using CadQuery. You'll learn how to create paths, define shapes, and use the sweep operation to generate complex 3D geometry. We'll examine various examples of sweeping shapes, highlighting the importance of shape placement and path definition.\n",
    "\n",
    "### Script Explanation\n",
    "\n",
    "#### Default Sweep\n",
    "1. **Define Path**: A path is created along the XZ plane with a length of 20.0 units.\n",
    "2. **Create Default Sweep**: A series of circles with diameters 2.0, 1.0, and 2.0 are defined at different offsets along the YZ plane. These circles are then swept along the defined path using the `sweep()` function with `multisection=True`.\n",
    "\n",
    "#### Circle to Rectangle Sweep\n",
    "1. **Define Path**: Same as the default sweep.\n",
    "2. **Create Circle to Rectangle Sweep**: This example demonstrates sweeping from a rectangle to a circle. Rectangles and circles are defined at different offsets along the YZ plane and then swept along the path.\n",
    "\n",
    "#### Rectangle to Circle Sweep\n",
    "1. **Define Path**: Same as the default sweep.\n",
    "2. **Create Rectangle to Circle Sweep**: Similar to the previous example, but this time sweeping from a circle to a rectangle.\n",
    "\n",
    "#### Special Sweep\n",
    "1. **Create Special Sweep**: This example showcases the importance of shape placement. Circles and rectangles are defined without proper alignment along the YZ plane, resulting in unexpected shapes when swept along the path.\n",
    "\n",
    "#### Arc Sweep\n",
    "1. **Define Path**: An arc path is defined, consisting of a line segment and a half circle with specified radii.\n",
    "2. **Create Arc Sweep**: Different cylinders are defined along the path and then swept to create a complex geometry.\n",
    "\n",
    "### Modifying the Example\n",
    "\n",
    "You can modify the script by adjusting the dimensions, shapes, and path definitions to create various sweeping patterns and shapes. Experiment with different path geometries, such as lines, arcs, or splines, and explore how they influence the resulting swept geometry.\n",
    "\n",
    "Additionally, you can change the placement and orientation of shapes along the path to achieve different visual effects and designs. Try combining multiple shapes, varying their sizes, or applying rotations to create intricate 3D models."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# X axis line length 20.0\n",
    "path = cq.Workplane(\"XZ\").moveTo(-10, 0).lineTo(10, 0)\n",
    "\n",
    "# Sweep a circle from diameter 2.0 to diameter 1.0 to diameter 2.0 along X axis length 10.0 + 10.0\n",
    "defaultSweep = (\n",
    "    cq.Workplane(\"YZ\")\n",
    "    .workplane(offset=-10.0)\n",
    "    .circle(2.0)\n",
    "    .workplane(offset=10.0)\n",
    "    .circle(1.0)\n",
    "    .workplane(offset=10.0)\n",
    "    .circle(2.0)\n",
    "    .sweep(path, multisection=True)\n",
    ")\n",
    "\n",
    "# We can sweep through different shapes\n",
    "recttocircleSweep = (\n",
    "    cq.Workplane(\"YZ\")\n",
    "    .workplane(offset=-10.0)\n",
    "    .rect(2.0, 2.0)\n",
    "    .workplane(offset=8.0)\n",
    "    .circle(1.0)\n",
    "    .workplane(offset=4.0)\n",
    "    .circle(1.0)\n",
    "    .workplane(offset=8.0)\n",
    "    .rect(2.0, 2.0)\n",
    "    .sweep(path, multisection=True)\n",
    ")\n",
    "\n",
    "circletorectSweep = (\n",
    "    cq.Workplane(\"YZ\")\n",
    "    .workplane(offset=-10.0)\n",
    "    .circle(1.0)\n",
    "    .workplane(offset=7.0)\n",
    "    .rect(2.0, 2.0)\n",
    "    .workplane(offset=6.0)\n",
    "    .rect(2.0, 2.0)\n",
    "    .workplane(offset=7.0)\n",
    "    .circle(1.0)\n",
    "    .sweep(path, multisection=True)\n",
    ")\n",
    "\n",
    "\n",
    "# Placement of the Shape is important otherwise could produce unexpected shape\n",
    "specialSweep = (\n",
    "    cq.Workplane(\"YZ\")\n",
    "    .circle(1.0)\n",
    "    .workplane(offset=10.0)\n",
    "    .rect(2.0, 2.0)\n",
    "    .sweep(path, multisection=True)\n",
    ")\n",
    "\n",
    "# Switch to an arc for the path : line l=5.0 then half circle r=4.0 then line l=5.0\n",
    "path = (\n",
    "    cq.Workplane(\"XZ\")\n",
    "    .moveTo(-5, 4)\n",
    "    .lineTo(0, 4)\n",
    "    .threePointArc((4, 0), (0, -4))\n",
    "    .lineTo(-5, -4)\n",
    ")\n",
    "\n",
    "# Placement of different shapes should follow the path\n",
    "# cylinder r=1.5 along first line\n",
    "# then sweep along arc from r=1.5 to r=1.0\n",
    "# then cylinder r=1.0 along last line\n",
    "arcSweep = (\n",
    "    cq.Workplane(\"YZ\")\n",
    "    .workplane(offset=-5)\n",
    "    .moveTo(0, 4)\n",
    "    .circle(1.5)\n",
    "    .workplane(offset=5, centerOption=\"CenterOfMass\")\n",
    "    .circle(1.5)\n",
    "    .moveTo(0, -8)\n",
    "    .circle(1.0)\n",
    "    .workplane(offset=-5, centerOption=\"CenterOfMass\")\n",
    "    .circle(1.0)\n",
    "    .sweep(path, multisection=True)\n",
    ")\n",
    "\n",
    "\n",
    "# Translate the resulting solids so that they do not overlap and display them left to right\n",
    "show(defaultSweep,\n",
    "     circletorectSweep.translate((0, 5, 0)),\n",
    "     recttocircleSweep.translate((0, 10, 0)),\n",
    "     specialSweep.translate((0, 15, 0)),\n",
    "     arcSweep.translate((0, 20, 0)),\n",
    "     names=[\n",
    "         'Default Sweep',\n",
    "         'Circle to Rectangle',\n",
    "         'Rectangle to circle',\n",
    "         'Special',\n",
    "         'Arc'\n",
    "         ],\n",
    "         colors=[\n",
    "             'red',\n",
    "             'orange',\n",
    "             'green',\n",
    "             'blue',\n",
    "             'purple'])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Helix"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this example, we'll create a helical shape using CadQuery by sweeping a 2D shape along a helix. You'll learn how to define parameters for the helix, create the helical path, and sweep a 2D shape along it to generate a helical geometry.\n",
    "\n",
    "### Script Explanation\n",
    "\n",
    "1. **Define Parameters**: Parameters such as the radius (`r`), pitch (`p`), and height (`h`) of the helix are defined. These parameters determine the characteristics of the helical shape.\n",
    "\n",
    "2. **Create Helix Wire**: A helix wire is generated using the `cq.Wire.makeHelix()` function, specifying the pitch, height, and radius of the helix. This wire represents the path along which the shape will be swept.\n",
    "\n",
    "3. **Define 2D Shape**: A 2D shape is defined on the XZ plane using the `cq.Workplane(\"XZ\")` constructor. This shape will be swept along the helix to create the helical geometry.\n",
    "\n",
    "4. **Sweep Operation**: The defined 2D shape is swept along the helix wire using the `sweep()` function. The `isFrenet=True` parameter ensures that the orientation of the shape remains consistent along the helix, resulting in a smooth helical geometry.\n",
    "\n",
    "### Modifying the Example\n",
    "\n",
    "You can modify the script by adjusting the parameters of the helix (`r`, `p`, `h`) to create helices of different sizes and dimensions. Experiment with varying the radius, pitch, and height to generate helices with different shapes and proportions.\n",
    "\n",
    "Additionally, you can change the 2D shape that is swept along the helix to create different helical profiles. Try defining different shapes, such as circles, rectangles, or polygons, and explore how they influence the resulting helical geometry.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define helix parameters\n",
    "r = 0.5  # Radius of the helix\n",
    "p = 0.4  # Pitch of the helix - vertical distance between loops\n",
    "h = 2.4  # Height of the helix - total height\n",
    "\n",
    "# Set helix based on wire dimensions\n",
    "wire = cq.Wire.makeHelix(pitch=p, height=h, radius=r)\n",
    "helix = cq.Workplane(obj=wire)\n",
    "\n",
    "# Final result: A 2D shape swept along a helix.\n",
    "result = (\n",
    "    cq.Workplane(\"XZ\")  # helix is moving up the Z axis\n",
    "    .center(r, 0)  # offset isosceles trapezoid\n",
    "    .polyline(((-0.15, 0.1), (0.0, 0.05), (0, 0.35), (-0.15, 0.3)))\n",
    "    .close()  # make edges a wire\n",
    "    .sweep(helix, isFrenet=True)  # Frenet keeps orientation as expected\n",
    ")\n",
    "\n",
    "show(result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Intermediate"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Complex Surfaces"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this example, we'll create complex 3D plates using CadQuery, demonstrating various techniques for generating intricate geometries. You'll learn how to define edge profiles, surface points, and optional parameters to customize the plate's appearance and properties.\n",
    "\n",
    "### Script Explanation\n",
    "\n",
    "#### Example 0\n",
    "1. **Create Plate with Zero Thickness**: A plate with zero thickness is created using the `interpPlate()` function. Edge points and surface points are defined, and the plate is translated to a specific position.\n",
    "\n",
    "#### Example 1\n",
    "1. **Create Plate with Bumps**: A plate with five sides and two bumps is created using the `interpPlate()` function. Edge points and surface points are defined, and the plate's volume is calculated.\n",
    "\n",
    "#### Example 2\n",
    "1. **Create Embossed Star**: An embossed star shape is created using the `interpPlate()` function. Edge points and surface points are defined, along with various optional parameters to control the plate's appearance.\n",
    "\n",
    "#### Example 3\n",
    "1. **Create Hexagonal Pattern**: A plate with a hexagonal pattern is created using the `interpPlate()` function. Edge points and surface points are defined using pushpoints, and optional parameters are adjusted to achieve the desired result.\n",
    "\n",
    "#### Example 4\n",
    "1. **Create Gyroid Structure**: A gyroïd structure is created using the `interpPlate()` function. Edge points and surface points are defined using splines on different workplanes, resulting in a complex geometric shape.\n",
    "\n",
    "### Modifying the Example\n",
    "\n",
    "You can modify the script by adjusting the parameters, edge profiles, and surface points to create custom plates with unique shapes and features. Experiment with different edge configurations, surface patterns, and optional parameters to achieve the desired geometry and appearance.\n",
    "\n",
    "Additionally, you can explore other CadQuery features and operations to further customize the plates. Try adding fillets, chamfers, or patterns to enhance the design according to your preferences.\n",
    "\n",
    "Feel free to experiment and explore the possibilities of creating complex plates with CadQuery, unlocking a range of creative opportunities in parametric 3D modeling.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Example 0\n",
    "# Curved surface - use of thickness = 0 returns 2D surface.\n",
    "thickness = 0\n",
    "edge_points = [(0.0, 0.0, 0.0), (0.0, 10.0, 0.0), (0.0, 10.0, 10.0), (0.0, 0.0, 10.0)]\n",
    "surface_points = [(5.0, 5.0, 5.0)]\n",
    "plate_0 = cq.Workplane(\"XY\").interpPlate(edge_points, surface_points, thickness)\n",
    "print(\"plate_0.val().Volume() = \", plate_0.val().Volume())\n",
    "plate_0 = plate_0.translate((0, 6 * 12, 0))\n",
    "\n",
    "# EXAMPLE 1\n",
    "# Plate with 5 sides and 2 bumps, one side is not co-planar with the other sides\n",
    "thickness = 0.1\n",
    "edge_points = [\n",
    "    (-7.0, -7.0, 0.0),\n",
    "    (-3.0, -10.0, 3.0),\n",
    "    (7.0, -7.0, 0.0),\n",
    "    (7.0, 7.0, 0.0),\n",
    "    (-7.0, 7.0, 0.0),\n",
    "]\n",
    "edge_wire = cq.Workplane(\"XY\").polyline(\n",
    "    [(-7.0, -7.0), (7.0, -7.0), (7.0, 7.0), (-7.0, 7.0)]\n",
    ")\n",
    "edge_wire = edge_wire.add(\n",
    "    cq.Workplane(\"YZ\")\n",
    "    .workplane()\n",
    "    .transformed(offset=cq.Vector(0, 0, -7), rotate=cq.Vector(45, 0, 0))\n",
    "    .spline([(-7.0, 0.0), (3, -3), (7.0, 0.0)])\n",
    ")\n",
    "surface_points = [(-3.0, -3.0, -3.0), (3.0, 3.0, 3.0)]\n",
    "plate_1 = cq.Workplane(\"XY\").interpPlate(edge_wire, surface_points, thickness)\n",
    "print(\"plate_1.val().Volume() = \", plate_1.val().Volume())\n",
    "\n",
    "# EXAMPLE 2\n",
    "# Embossed star, need to change optional parameters to obtain nice looking result.\n",
    "r1 = 3.0\n",
    "r2 = 10.0\n",
    "fn = 6\n",
    "thickness = 0.1\n",
    "edge_points = [\n",
    "    (r1 * cos(i * pi / fn), r1 * sin(i * pi / fn))\n",
    "    if i % 2 == 0\n",
    "    else (r2 * cos(i * pi / fn), r2 * sin(i * pi / fn))\n",
    "    for i in range(2 * fn + 1)\n",
    "]\n",
    "edge_wire = cq.Workplane(\"XY\").polyline(edge_points)\n",
    "r2 = 4.5\n",
    "surface_points = [\n",
    "    (r2 * cos(i * pi / fn), r2 * sin(i * pi / fn), 1.0) for i in range(2 * fn)\n",
    "] + [(0.0, 0.0, -2.0)]\n",
    "plate_2 = cq.Workplane(\"XY\").interpPlate(\n",
    "    edge_wire,\n",
    "    surface_points,\n",
    "    thickness,\n",
    "    combine=True,\n",
    "    clean=True,\n",
    "    degree=3,\n",
    "    nbPtsOnCur=15,\n",
    "    nbIter=2,\n",
    "    anisotropy=False,\n",
    "    tol2d=0.00001,\n",
    "    tol3d=0.0001,\n",
    "    tolAng=0.01,\n",
    "    tolCurv=0.1,\n",
    "    maxDeg=8,\n",
    "    maxSegments=49,\n",
    ")\n",
    "print(\"plate_2.val().Volume() = \", plate_2.val().Volume())\n",
    "plate_2 = plate_2.translate((0, 2 * 12, 0))\n",
    "\n",
    "# EXAMPLE 3\n",
    "# Points on hexagonal pattern coordinates, use of pushpoints.\n",
    "r1 = 1.0\n",
    "N = 3\n",
    "ca = cos(30.0 * pi / 180.0)\n",
    "sa = sin(30.0 * pi / 180.0)\n",
    "# EVEN ROWS\n",
    "pts = [\n",
    "    (-3.0, -3.0),\n",
    "    (-1.267949, -3.0),\n",
    "    (0.464102, -3.0),\n",
    "    (2.196152, -3.0),\n",
    "    (-3.0, 0.0),\n",
    "    (-1.267949, 0.0),\n",
    "    (0.464102, 0.0),\n",
    "    (2.196152, 0.0),\n",
    "    (-2.133974, -1.5),\n",
    "    (-0.401923, -1.5),\n",
    "    (1.330127, -1.5),\n",
    "    (3.062178, -1.5),\n",
    "    (-2.133975, 1.5),\n",
    "    (-0.401924, 1.5),\n",
    "    (1.330127, 1.5),\n",
    "    (3.062178, 1.5),\n",
    "]\n",
    "# Spike surface\n",
    "thickness = 0.1\n",
    "fn = 6\n",
    "edge_points = [\n",
    "    (\n",
    "        r1 * cos(i * 2 * pi / fn + 30 * pi / 180),\n",
    "        r1 * sin(i * 2 * pi / fn + 30 * pi / 180),\n",
    "    )\n",
    "    for i in range(fn + 1)\n",
    "]\n",
    "surface_points = [\n",
    "    (\n",
    "        r1 / 4 * cos(i * 2 * pi / fn + 30 * pi / 180),\n",
    "        r1 / 4 * sin(i * 2 * pi / fn + 30 * pi / 180),\n",
    "        0.75,\n",
    "    )\n",
    "    for i in range(fn + 1)\n",
    "] + [(0, 0, 2)]\n",
    "edge_wire = cq.Workplane(\"XY\").polyline(edge_points)\n",
    "plate_3 = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .pushPoints(pts)\n",
    "    .interpPlate(\n",
    "        edge_wire,\n",
    "        surface_points,\n",
    "        thickness,\n",
    "        combine=False,\n",
    "        clean=False,\n",
    "        degree=2,\n",
    "        nbPtsOnCur=20,\n",
    "        nbIter=2,\n",
    "        anisotropy=False,\n",
    "        tol2d=0.00001,\n",
    "        tol3d=0.0001,\n",
    "        tolAng=0.01,\n",
    "        tolCurv=0.1,\n",
    "        maxDeg=8,\n",
    "        maxSegments=9,\n",
    "    )\n",
    ")\n",
    "print(\"plate_3.val().Volume() = \", plate_3.val().Volume())\n",
    "plate_3 = plate_3.translate((0, 4 * 11, 0))\n",
    "\n",
    "# EXAMPLE 4\n",
    "# Gyroïd, all edges are splines on different workplanes.\n",
    "thickness = 0.1\n",
    "edge_points = [\n",
    "    [[3.54, 3.54], [1.77, 0.0], [3.54, -3.54]],\n",
    "    [[-3.54, -3.54], [0.0, -1.77], [3.54, -3.54]],\n",
    "    [[-3.54, -3.54], [0.0, -1.77], [3.54, -3.54]],\n",
    "    [[-3.54, -3.54], [-1.77, 0.0], [-3.54, 3.54]],\n",
    "    [[3.54, 3.54], [0.0, 1.77], [-3.54, 3.54]],\n",
    "    [[3.54, 3.54], [0.0, 1.77], [-3.54, 3.54]],\n",
    "]\n",
    "plane_list = [\"XZ\", \"XY\", \"YZ\", \"XZ\", \"YZ\", \"XY\"]\n",
    "offset_list = [-3.54, 3.54, 3.54, 3.54, -3.54, -3.54]\n",
    "edge_wire = (\n",
    "    cq.Workplane(plane_list[0]).workplane(offset=-offset_list[0]).spline(edge_points[0])\n",
    ")\n",
    "for i in range(len(edge_points) - 1):\n",
    "    edge_wire = edge_wire.add(\n",
    "        cq.Workplane(plane_list[i + 1])\n",
    "        .workplane(offset=-offset_list[i + 1])\n",
    "        .spline(edge_points[i + 1])\n",
    "    )\n",
    "surface_points = [(0, 0, 0)]\n",
    "plate_4 = cq.Workplane(\"XY\").interpPlate(edge_wire, surface_points, thickness)\n",
    "print(\"plate_4.val().Volume() = \", plate_4.val().Volume())\n",
    "plate_4 = plate_4.translate((0, 5 * 12, 0))\n",
    "show(plate_0,\n",
    "     plate_1,\n",
    "     plate_2,\n",
    "     plate_3,\n",
    "     plate_4,\n",
    "     names=[\n",
    "         '2D Surface',\n",
    "         'Hilly Surface',\n",
    "         'Embossed Star',\n",
    "         'Patterned Spikes',\n",
    "         'Gyroid'\n",
    "        ],\n",
    "    colors=[\n",
    "         'purple',\n",
    "         'red',\n",
    "         'orange',\n",
    "         'green',\n",
    "         'blue'\n",
    "        ],\n",
    "    )"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Cycloid Gear"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In this example, we'll create gear profiles using parametric curves in CadQuery. You'll learn how to define generating functions for hypocycloids and epicycloids, and use them to create complex gear shapes. We'll also demonstrate the `parametricCurve()` and `twistExtrude()` functions to generate 3D geometry from the parametric curves.\n",
    "\n",
    "### Script Explanation\n",
    "\n",
    "#### Defining Generating Functions\n",
    "1. **Hypocycloid Function**: Defines a generating function for hypocycloids, which are curves traced by a point on a smaller circle rolling inside a larger circle.\n",
    "2. **Epicycloid Function**: Defines a generating function for epicycloids, which are curves traced by a point on a larger circle rolling outside a smaller circle.\n",
    "3. **Gear Function**: Combines the hypocycloid and epicycloid functions to create a gear profile. The gear function determines whether to use an epicycloid or hypocycloid based on the gear's teeth.\n",
    "\n",
    "#### Create Gear Profile and Extrude\n",
    "1. **Parametric Curve**: Defines a parametric curve using the gear function to generate the gear profile.\n",
    "2. **Twist Extrude**: Extrudes the gear profile along a twist path to create a 3D representation of the gear.\n",
    "3. **Cut Through All**: Cuts the gear shape through all faces to ensure a solid geometry.\n",
    "\n",
    "### Modifying the Example\n",
    "\n",
    "You can modify the script by adjusting the parameters of the generating functions (`r1`, `r2`) to create gears with different sizes and numbers of teeth. Experiment with varying the radius ratios and angular offsets to generate custom gear profiles.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define the generating function\n",
    "def hypocycloid(t, r1, r2):\n",
    "    return (\n",
    "        (r1 - r2) * cos(t) + r2 * cos(r1 / r2 * t - t),\n",
    "        (r1 - r2) * sin(t) + r2 * sin(-(r1 / r2 * t - t)),\n",
    "    )\n",
    "\n",
    "\n",
    "def epicycloid(t, r1, r2):\n",
    "    return (\n",
    "        (r1 + r2) * cos(t) - r2 * cos(r1 / r2 * t + t),\n",
    "        (r1 + r2) * sin(t) - r2 * sin(r1 / r2 * t + t),\n",
    "    )\n",
    "\n",
    "\n",
    "def gear(t, r1=4, r2=1):\n",
    "    if (-1) ** (1 + floor(t / 2 / pi * (r1 / r2))) < 0:\n",
    "        return epicycloid(t, r1, r2)\n",
    "    else:\n",
    "        return hypocycloid(t, r1, r2)\n",
    "\n",
    "\n",
    "# Create the gear profile and extrude it\n",
    "result = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .parametricCurve(lambda t: gear(t * 2 * pi, 6, 1))\n",
    "    .twistExtrude(15, 90)\n",
    "    .faces(\">Z\")\n",
    "    .workplane()\n",
    "    .circle(2)\n",
    "    .cutThruAll()\n",
    ")\n",
    "\n",
    "show(result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Advanced Example"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Go to the file named `Advanced_Example_Hexapod.ipynb` to see a full assembly robotic insect! No need to modify this one. It is just meant to show what cool things you can do with cadquery!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Project Challenge"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Use what you've learned along with additional resources (see below) to make your very own CAD model! CAD is capable of designing almost anything you can imagine. Here are some starter possibilities, but feel free to choose something of your own interest:\n",
    "1. A table\n",
    "2. A chair\n",
    "3. A computer\n",
    "4. A mechanical clock\n",
    "5. A building"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Additional Resources\n",
    "\n",
    "For more examples:\n",
    "- https://github.com/CadQuery/cadquery/tree/master/examples\n",
    "\n",
    "- https://cadquery.readthedocs.io/en/latest/examples.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "psuccess_3_10",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
